service: cookyt

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-3
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

