service: commandant

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev

functions:
  handler:
    handler: index.handler
    events:
      - alexaSkill: 
        appId: ${env:ALEXA_APP_ID}
        enabled: true

